---
- name: User palybook
  hosts: all
  become: yes
  become_method: sudo
  user: centos
  tasks:

  - name: add user bob
    user:
      name: bob
      comment: "John Smith"
      groups: wheel
      generate_ssh_key: yes
      state: present

  - name: remove user Lisa
    user:
      name: Lisa
      state: absent

